# Generated by Django 2.2.4 on 2019-11-01 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaCuentas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.IntegerField()),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categoría',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=6)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fkCategoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.CategoriaCuentas')),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=15)),
                ('telefono', models.CharField(max_length=15)),
                ('nit', models.CharField(max_length=15)),
                ('codigo', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField()),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=6)),
                ('iva', models.DecimalField(decimal_places=2, max_digits=4)),
                ('retencion', models.DecimalField(decimal_places=2, max_digits=4)),
                ('fkEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Empresa')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDebe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fkCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroHaber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fkCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Cuenta')),
            ],
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('fkRegistroDebe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.RegistroDebe')),
                ('fkRegistroHaber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.RegistroHaber')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=15)),
                ('nombre', models.CharField(max_length=15)),
                ('existencia', models.IntegerField()),
                ('fkCategoría', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='LineaDeVenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=6)),
                ('fkFactura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Factura')),
                ('fkProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='informesContables.Producto')),
            ],
        ),
    ]
