# Generated by Django 2.2.4 on 2019-11-03 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informesContables', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
            ],
        ),
    ]
