# Generated by Django 2.2.4 on 2019-11-03 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('informesContables', '0002_insumo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoriacuentas',
            name='tipo',
        ),
    ]
