# Generated by Django 2.2.4 on 2019-11-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informesContables', '0003_remove_categoriacuentas_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoriacuentas',
            name='tipo',
            field=models.CharField(default='Activo', max_length=10),
        ),
    ]
