# Generated by Django 2.2.4 on 2019-11-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informesContables', '0006_auto_20191103_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriacuentas',
            name='nombre',
            field=models.CharField(default='Activo', max_length=20),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='lineadeventa',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, max_digits=16),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='registrodebe',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='registrohaber',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
