# Generated by Django 2.2.4 on 2019-11-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informesContables', '0007_auto_20191103_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='idCuenta',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
